// models/Supplier.js
const mongoose = require('mongoose');

const supplierSchema = new mongoose.Schema({
    supplierName: { type: String },
    phoneNumber: { type: String },
    mobileNumber: { type: String },
    address: { type: String },
    emailId: { type: String },
    website: { type: String },
    city: { type: String },
    pinCode: { type: String },
    panNo: { type: String },
    priceList: { type: String },
    country: { type: String },
    opening: { type: String },
    loyalityNo: { type: String },
    GSTno: { type: String },
    dueDays: { type: String },
    formalName: { type: String },
    openBill: { type: String },
    bank: { type: String },
    isActive: { type: String },
    allowCredit: { type: String },
    purchaseData: [{
        purchaseNumber: { type: String },
        deliveryDate: { type: Date },
        invoiceNumber: { type: String },
        itemDescription: { type: String },
        invoiceDate: { type: Date },
        barcode: { type: String },
        itemsData: [{
            sl_no: { type: Number },
            item: { type: String },
            qty: { type: Number },
            uom: { type: String },
            rate: { type: Number },
            discount: { type: Number },
            netRate: { type: Number },
            amount: { type: Number },
            netAmount: { type: Number },
            cgst: { type: Number },
            sgst: { type: Number },
            groupName: { type: String },
            margin: { type: Number },
            MRP: { type: Number },
            salesRate: { type: Number },
            minRate: { type: Number },
            paymentMode: { type: String },
            tenderedAmount: { type: Number },
            balanceAmount: { type: Number },
            discountAmount: { type: Number },
            brand: { type: String },
            itemCode: { type: String },
            minimumRate: { type: Number },
            minStock: { type: Number },
            location: { type: String },
            hasBatch: { type: String },
            isActive: { type: String },
            isFMP: { type: String },
        }]
    }]
});

module.exports = mongoose.model('Supplier', supplierSchema);
